version: "3"

services:
  twitter-app:
    build:
      context: .
      args:
        - node_version=14.5-alpine
    image: "jlocken/hashtag-twitter-app:${IMAGE_TAG}"
    container_name: hashtag-twitter-app
    env_file:
        - .env
    ports:
       - "${HOST_PORT}:3000"



    
